# Generated by Django 3.0.8 on 2020-08-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название изображения')),
                ('tags', models.CharField(max_length=30, verbose_name='Тэги')),
                ('img', models.ImageField(upload_to='user_image', verbose_name='Загрузите изображение')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_title', models.CharField(max_length=20, verbose_name='Название альбома')),
                ('album_image', models.ManyToManyField(to='gallery.Image', verbose_name='Выбор изображения')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
                'ordering': ['id'],
            },
        ),
    ]
